//This is the to-be compiled text-based class for SeeR. DO NOT EDIT!!!

char Vertex[]={"struct Vertex\n"
"{\n"
" double vx;\n"
" double vy;\n"
" double vz;\n"
" int Index;\n"
" int BoolStat;\n"
" bool Selected;\n"
"c_import double GetDistance ( Vertex pt );\n"
"c_import bool GetSelected ( ) const;\n"
"c_import void SetSelected ( bool selected );\n"
"c_import bool operator== ( Vertex cmpt );\n"
"c_import bool operator!= ( Vertex cmpt );\n"
"c_import Vertex operator+ ( Vertex cmpt );\n"
"c_import Vertex operator- ( Vertex cmpt );\n"
"c_import Vertex operator* ( int cmpt );\n"
"c_import Vertex operator* ( Vertex cmpt );\n"
"c_import void operator-= ( Vertex cmpt );\n"
"c_import void operator+= ( Vertex cmpt );\n"
"c_import void operator*= ( Vertex cmpt );\n"
"c_import void operator*= ( double cmpt );\n"
"c_import void operator/= ( int cmpt );\n"
"c_import Vertex operator/ ( double cmpt );\n"
"c_import void operator= ( double cmpt );\n"
"c_import void operator= ( Vertex cmpt );\n"
"c_import Vertex RotVect ( Vertex Vect , double ng );\n"
"c_import bool IsEquivalentTo ( Vertex cmpt );\n"
"c_import void Snap ( Vertex SnapVal );\n"
"c_import void GetMinOf ( Vertex vert );\n"
"c_import void GetMaxOf ( Vertex vert );\n"
"c_import double Normalize ( void );\n"
"c_import double Dot ( Vertex pVec );\n"
"c_import void Cross ( Vertex & p , Vertex & q );\n"
"};\n"};
