//This is the to-be compiled text-based class for SeeR. DO NOT EDIT!!!

char Desk[]={"struct Desk\n"
"{\n"
" Desk* Prev ,* Next;\n"
" Shape* NextShape ,* FirstShape;\n"
"c_import AddShape ( );\n"
"c_import InsertShape ( Shape* InsShape );\n"
" Shape* Sel;\n"
" Selection* cSel;\n"
"c_import DelSkeletton ( Skeletton* daSkel );\n"
"c_import DelShape ( Shape* daShape );\n"
"c_import DelObject ( Object* daObj );\n"
"c_import bool DelShapeSeg ( void );\n"
" Camera* NextCam ,* FirstCam;\n"
"c_import AddCam ( );\n"
"c_import DelCam ( Camera* daCam );\n"
"c_import Camera* GetCamera ( char* CamName );\n"
" Object* NextObject ,* FirstObject;\n"
"c_import AddObject ( );\n"
"c_import AddObject ( Object* daObj );\n"
"c_import Object* GetObject ( char* ObjName );\n"
" CPrivateData* NextData ,* FirstData;\n"
"c_import CPrivateData* AddPrivate ( char* Name );\n"
"c_import CPrivateData* GetPrivate ( char* Name );\n"
" Skeletton* NextSkel ,* FirstSkel;\n"
"c_import AddSkel ( );\n"
"c_import AddPath ( );\n"
" CTexture* NextTexture ,* FirstTexture;\n"
"c_import CTexture* AddTex ( char* TexName );\n"
" char* FileName;\n"
" char* Name;\n"
" bool IsNamed;\n"
"c_import void SetName ( char* val );\n"
" VertBuf* FirstBufVert ,* NextBufVert;\n"
"c_import void AddBufVert ( Vertex* DaVert , int Index= 0 );\n"
"c_import void AddBufVert ( Vertex* DaVert , Object* Obj , int Index= 0 );\n"
"c_import void DeleteBufVert ( void );\n"
"c_import void TranslateBuf ( Vertex Trans );\n"
"c_import void Flush ( void );\n"
"c_import void UpdateBuf ( void );\n"
"c_import void RotateBuf ( Plan* dap , Vertex Center );\n"
"c_import void ScaleBuf ( Plan* dap , Vertex Center , Vertex ScaleVal );\n"
"c_import Vertex GetMinBuf ( void );\n"
"c_import Vertex GetMaxBuf ( void );\n"
"c_import void RemoveBufUnselected ( void );\n"
"c_import void CopySelectedTo ( Desk* DstDk );\n"
"c_import void DeleteSelected ( void );\n"
" Light* FirstLight ,* NextLight;\n"
"c_import AddLight ( );\n"
"c_import DelLight ( Light* daLight );\n"
" Script* FirstScript ,* NextScript;\n"
"c_import AddScript ( );\n"
" bool Modified;\n"
" char* temp;\n"
" int FrameInd;\n"
"c_import bool GetMinOf ( long Stat , Vertex* Dest );\n"
"c_import bool GetMaxOf ( long Stat , Vertex* Dest );\n"
" Vertex Axis;\n"
"c_import void SetAxis ( Vertex daAxis );\n"
" bool FullScreen;\n"
" Camera** cam;\n"
" float* light1_pos;\n"
" Vertex* ViewNg ,* ViewPos ,* ViewSize ,* tmppos ,* tmpViewSize ,* TmpViewNg;\n"
" POINT* ViewStart ,* ViewEnd;\n"
" int* ViewType;\n"
" int Active;\n"
" int AncActive;\n"
" int** viewport;\n"
" double** mvmatrix ,** projmatrix;\n"
" int viewport2;\n"
" double* mvmatrix2 ,* projmatrix2;\n"
"c_import void ComputeSize ( void );\n"
"c_import bool SetActive ( int X , int Y );\n"
" float aspect , Height , Width , Left , Top;\n"
" int* State;\n"
"c_import void ReSize ( int daWidth , int daHeight );\n"
" int daViewMode;\n"
" int TabId;\n"
"c_import bool DelShapeVert ( void );\n"
" bool Snap , Crossing , Center;\n"
" Vertex SnapVal;\n"
" char* CurrentName;\n"
"c_import bool GenerateName ( int NameType );\n"
"c_import void* GetByName ( char name [ 20 ] , int NameType );\n"
" Vertex snap;\n"
" CSkyBox* daSky;\n"
" CMaps* maps;\n"
"c_import void DeleteAll ( void );\n"
" Camera Perspective;\n"
"c_import void AddKF ( void );\n"
"};\n"};
