//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TerrainEd.rc
//
#define IDD_TERRAINED_DIALOG            102
#define IDB_BITMAP                      104
#define IDB_BITMAPHOT                   105
#define IDR_MAINFRAME                   128
#define IDD_PREVIEW                     129
#define IDR_ECORCE                      130
#define IDR_FEUILLES                    131
#define IDD_HEIGHTDESIGN                132
#define IDD_MAPEDIT                     134
#define IDR_SPLASH                      136
#define IDD_SPLASH                      139
#define IDD_TREEDESIGN                  140
#define IDD_SKYBOX                      207
#define IDC_SCROLLBAR1                  1000
#define IDC_SCROLLBAR2                  1001
#define IDC_CHECK1                      1002
#define IDC_GENERATE                    1003
#define IDC_CHECK2                      1004
#define IDC_PZ                          1005
#define IDC_CHECK3                      1006
#define IDC_SLIDER1                     1007
#define IDC_CHECK4                      1008
#define IDC_WATER                       1009
#define IDC_CHECK5                      1010
#define IDC_ANGLE                       1011
#define IDC_CHECK6                      1012
#define IDC_LIGHT                       1013
#define IDC_CHECK7                      1014
#define IDC_CL2UP                       1015
#define IDC_SUN                         1016
#define IDC_CHECK8                      1017
#define IDC_CL2DOWN                     1018
#define IDC_SLIDER2                     1019
#define IDC_CHECK9                      1020
#define IDC_CL2LEFT                     1021
#define IDC_SLIDER3                     1022
#define IDC_CHECK10                     1023
#define IDC_CL2RIGHT                    1024
#define IDC_SLIDER4                     1025
#define IDC_CHECK11                     1026
#define IDC_CL2FRONT                    1027
#define IDC_SLIDER5                     1028
#define IDC_CHECK12                     1029
#define IDC_CL2BACK                     1030
#define IDC_BTTEX1                      1031
#define IDC_CHECK13                     1032
#define IDC_BTTEX2                      1033
#define IDC_CHECK14                     1034
#define IDC_BTTEX4                      1035
#define IDC_CHECK15                     1036
#define IDC_BTTEX3                      1037
#define IDC_SIZELAND                    1037
#define IDC_CHECK16                     1038
#define IDC_SLIDER6                     1039
#define IDC_DOOBJECT                    1039
#define IDC_CHECK17                     1040
#define IDC_SLIDER7                     1041
#define IDC_CHECK18                     1042
#define IDC_BTTEX5                      1043
#define IDC_CHECK19                     1044
#define IDC_BTTEX6                      1045
#define IDC_CHECK20                     1046
#define IDC_SCROLLBAR7                  1047
#define IDC_BUTTON1                     1048
#define IDC_SCROLLBAR8                  1049
#define IDC_BUTTON2                     1050
#define IDC_SCROLLBAR9                  1051
#define IDC_BUTTON3                     1052
#define IDC_SCROLLBAR10                 1053
#define IDC_BUTTON4                     1054
#define IDC_PREVIEW                     1055
#define IDC_BLURLIGHTMAP2               1056
#define IDC_SLOP                        1057
#define IDC_SLIDERZ1                    1057
#define IDC_BUTTON5                     1058
#define IDC_EXPORT                      1059
#define IDC_SLIDERZ2                    1059
#define IDC_HEIGHTWIN                   1060
#define IDC_SLIDER8                     1061
#define IDC_BUTTON6                     1062
#define IDC_GENERATE2                   1063
#define IDC_LIGHTWIN                    1064
#define IDC_SLIDER9                     1065
#define IDC_BUTTON8                     1066
#define IDC_GENERATE3                   1067
#define IDC_BTTEX7                      1068
#define IDC_SKYBOX                      1069
#define IDC_BUTTON9                     1070
#define IDC_BTTEX8                      1071
#define IDC_IMPORT                      1072
#define IDC_BUTTON10                    1073
#define IDC_DETAIL                      1074
#define IDC_BUTTON11                    1075
#define IDC_LOADCONFIG                  1076
#define IDC_BUTTON12                    1077
#define IDC_SAVECONFIG                  1078
#define IDC_BUTTON13                    1079
#define IDC_BLURLIGHT                   1080
#define IDC_BUTTON14                    1081
#define IDC_SAVEMAP                     1082
#define IDC_BUTTON7                     1083
#define IDC_SAVE                        1084
#define IDC_LOAD                        1085
#define IDC_NEW                         1086
#define IDC_SKYBOXNAME                  1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
