//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ModifierRes.rc
//
#define IDD_MODDIAG                     101
#define IDB_BITMAP                      104
#define IDC_POINTER_FOUND               109
#define IDD_CALCTEX                     109
#define IDD_MODIFIER                    110
#define IDC_POINTER_NOTFOUND            110
#define IDD_EXTRUD                      111
#define IDD_SPHERIZE                    112
#define IDD_LATHE                       113
#define IDD_PATH                        114
#define IDD_UVPARAM                     115
#define IDD_EXPLODE                     116
#define IDD_NORMALS                     117
#define IDD_SUBDIVIDE                   118
#define IDD_FRACTALIZE                  119
#define IDD_DIVIDE                      120
#define IDD_UVEDIT                      121
#define IDD_PRECALC                     122
#define IDC_SHAPE                       1000
#define IDC_UP                          1001
#define IDC_PATH                        1001
#define IDC_LEFT                        1002
#define IDC_SPINPATH                    1003
#define IDC_UPDOWN                      1004
#define IDC_SPINSHAPE                   1004
#define IDC_LEFTRIGHT                   1005
#define IDC_UPDOWN2                     1006
#define IDC_LEFTRIGHT2                  1007
#define IDC_UPDOWN3                     1008
#define IDC_ROTATE                      1008
#define IDC_LEFTRIGHT3                  1009
#define IDC_ROTATEY                     1009
#define IDC_ANY                         1010
#define IDC_ROTATEZ                     1010
#define IDC_LOADMAP                     1010
#define IDC_CBVIEW                      1011
#define IDC_BENDHORZ                    1012
#define IDC_SHAPENAME                   1012
#define IDC_SELOBJECT                   1012
#define IDC_COL                         1012
#define IDC_FLIPNORMALS                 1013
#define IDC_PATHNAME                    1013
#define IDC_MAPPLANAR                   1013
#define IDC_MSIZE                       1013
#define IDC_BENDVERT                    1014
#define IDC_SLIDER1                     1014
#define IDC_MAPCUBE                     1014
#define IDC_DENSITY                     1014
#define IDC_LIBSTEPS                    1015
#define IDC_MAPSPHERICAL                1015
#define IDC_CALCULATE                   1015
#define IDC_SKEWHORZ                    1016
#define IDC_STEPS                       1016
#define IDC_MAPCYL                      1016
#define IDC_PROGRESS1                   1016
#define IDC_SQUIZHORZ                   1017
#define IDC_LIBLENGTH                   1017
#define IDC_LAYER1                      1017
#define IDC_WRITERAW                    1017
#define IDC_SYMETRY                     1018
#define IDC_SPINSTEPS                   1018
#define IDC_SPLINEDPATH                 1018
#define IDC_LAYER3                      1018
#define IDC_ROUND                       1018
#define IDC_SKEWVERT                    1019
#define IDC_LENGTH                      1019
#define IDC_SPLINEDSHAPE                1019
#define IDC_LAYER2                      1019
#define IDC_AMBIANT                     1019
#define IDC_SQUIZVERT                   1020
#define IDC_SPINLENGTH                  1020
#define IDC_LAYER4                      1020
#define IDC_UNIFYNORMALS                1021
#define IDC_LIBSCALE                    1021
#define IDC_APPLY                       1021
#define IDC_SCALE                       1022
#define IDC_BUTTON1                     1022
#define IDC_NEWSEED                     1022
#define IDC_ODIVIDE                     1022
#define IDC_OBJNAME                     1022
#define IDC_SPINSCALE                   1023
#define IDC_EDIT1                       1023
#define IDC_SCALEY                      1023
#define IDC_EDIT3                       1024
#define IDC_CHECK1                      1024
#define IDC_SPIN1                       1025
#define IDC_SPIN2                       1026
#define IDC_DIV2                        1027
#define IDC_SAVEBMP                     1027
#define IDC_DIV3                        1028
#define IDC_CAPPING                     1031
#define IDC_OEXPLODE                    1032
#define IDC_OEXTRUD                     1033
#define IDC_OFRACTALIZE                 1034
#define IDC_OLATHE                      1035
#define IDC_OBSP                        1036
#define IDC_ONORMALS                    1037
#define IDC_OPATH                       1038
#define IDC_OSPHERIZE                   1039
#define IDC_OTESSELATE                  1040
#define IDC_OUVMAPPING                  1041
#define IDC_LIGHTMAP                    1042
#define IDC_STEPSPATH                   1047
#define IDC_STEPSSHAPE                  1048
#define IDC_SPHERIZE                    2001
#define IDB_RX                          2001
#define IDB_SY                          2002
#define IDB_RY                          2003
#define IDB_SZ                          2004
#define IDB_RZ                          2005
#define IDB_SX                          2006
#define IDB_CLIPPER                     2007
#define IDB_CSGMERGE                    2008
#define IDB_CSGSUB                      2009
#define IDB_HOLLOW                      2011
#define IDB_BITMAPHOT                   2012
#define IDC_RX                          4005
#define IDC_SX                          4006
#define IDC_RY                          4007
#define IDC_SY                          4008
#define IDC_RZ                          4009
#define IDC_SZ                          4010
#define IDC_HOLLOW                      4011
#define IDC_CSGMERGE                    4012
#define IDC_CSGSUB                      4013
#define IDC_CLIPPER                     4025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
