//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by KapsulSE.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_LIGHTBULB                   101
#define IDD_SELNAME                     102
#define IDB_HCAM                        103
#define CG_IDS_DIDYOUKNOW               104
#define IDC_POINTER_MOVE                105
#define IDD_OPTIONS_EDITING             106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDS_FILE_CORRUPT             108
#define IDC_SELSINGLE                   109
#define IDR_MAINFRAME                   110
#define IDC_SELSINGLEFOUND              111
#define IDI_NEXTFRAME                   112
#define IDI_PLAY                        113
#define IDI_STOP                        114
#define IDI_KILLKF                      115
#define IDI_PREVFRAME                   116
#define IDR_KAPSULTYPE                  117
#define IDR_SELECTBAR                   118
#define IDB_BITMAP1                     119
#define IDR_VIEWCONFIG                  120
#define IDD_ANIM                        121
#define IDI_PAUSE                       122
#define IDI_PREVKF                      123
#define IDI_NEXTKF                      124
#define IDD_ANIMNBFRAMES                125
#define IDB_HLIGHT                      126
#define ID_Menu                         127
#define ID_VIEW_SKYBOX                  128
#define ID_SKYBOX_LOAD                  129
#define ID_SKYBOX_NONE                  130
#define ID_TOOLS_ENTITYMANAGER          131
#define IDR_HIERCTX                     132
#define IDR_MODIFY                      133
#define IDC_SPLITTER                    134
#define IDC_FPOINT                      135
#define IDD_ENTITYNAME                  136
#define IDD_ENTITYED                    137
#define IDC_STATIC1                     138
#define IDD_ENTITYTEST                  139
#define IDR_KAPSULSCRIPT                140
#define IDD_SELTYPEDOC                  141
#define IDR_KAPSULDESK                  142
#define IDR_TOOLBAR1                    143
#define IDR_SEER                        144
#define IDR_MODIFVIEW                   145
#define IDR_MODE                        146
#define IDC_NEXTTIP                     147
#define IDC_STARTUP                     148
#define IDC_TIPSTRING                   149
#define IDR_RENDER                      150
#define IDC_HANDOPEN                    151
#define IDC_HANDCLOSE                   152
#define IDC_STANDARD                    153
#define IDD_OPTIONS_MAPPATHS            154
#define IDR_CONTEXT                     155
#define ID_BUILD_COMPILE                156
#define IDR_PROJECTCTXPRJ               156
#define IDD_OBJPROPS                    157
#define IDR_PROJECTCTXFOLDER            157
#define ID_VIEW_ANIMATIONBAR            158
#define IDR_PROJECTCTXFILE              158
#define IDD_MATBROWSER                  159
#define IDD_DESKSBROWSER                160
#define IDD_TVTEST_DIALOG               161
#define IDD_ENTS_DIALOG                 162
#define IDB_MAINTOOLBAR                 163
#define IDB_MAINTOOLBAR2                164
#define IDB_MAINTOOLBAR3                165
#define IDD_ANIMOUTPUT                  166
#define IDD_OUTPUT                      167
#define IDR_MAINDESK                    168
#define IDB_DESKTOOLBAR                 169
#define IDB_DESKTOOLBAR3                170
#define IDB_DESKTOOLBAR2                171
#define IDR_ABOUTKAPSUL                 172
#define IDR_ABOUTESQUE                  173
#define IDR_ABOUT                       174
#define IDD_PRIMITIVES                  175
#define IDB_BMPLOW                      176
#define IDB_BMPHI                       177
#define IDB_SELSINGLENORMAL             178
#define IDB_SELCIRCLEHOT                179
#define ID_INDICATOR_CONTROLS           180
#define IDB_SELCIRCLENORMAL             181
#define ID_INDICATOR_MISC               182
#define IDB_SELFENCEHOT                 183
#define IDD_TIP                         184
#define IDB_SELFENCENORMAL              185
#define IDD_TSCROLL_DIALOG              186
#define IDB_SELQUADHOT                  187
#define IDD_SKYBOX                      188
#define IDB_SELQUADNORMAL               189
#define IDR_VIEWS                       190
#define IDD_OPTIONS                     191
#define IDR_MODIFY2                     192
#define IDD_EDITPLUGS                   193
#define IDR_MAINFRAME1                  194
#define IDC_NODRAGGING                  195
#define IDB_SELSINGLEHOT                196
#define IDB_SELMODEVERTEXLO             197
#define IDB_SELMODEFACELO               198
#define IDB_SELMODEOBJECT               199
#define IDB_SELMODEOBJECTLO             200
#define IDB_SELMODEVERTEX               201
#define IDB_SELMODEFACE                 202
#define IDB_DESKBUILD                   500
#define IDB_DESKHIERAR                  501
#define IDB_DESKMAPS                    502
#define IDD_TWEAKUV                     503
#define IDD_BACKIMAGE                   506
#define IDD_NEWPROJECT                  507
#define IDD_NEWFOLDER                   508
#define IDD_STATUSBAR                   509
#define IDB_STATUSSNAP                  510
#define IDB_STATUSCROSSING              511
#define IDB_STATUSCENTROID              512
#define IDB_STATUSANGLE                 513
#define IDB_STATUSSCALE                 514
#define IDB_STATUSCENTROIDNB            515
#define IDB_STATUSCROSSINGNB            516
#define IDB_STATUSSNAPNB                517
#define IDD_SELECTRENDERER              518
#define IDD_MATERIALEDITOR              525
#define IDD_RENDER                      526
#define IDB_Z                           527
#define IDB_Y                           528
#define IDB_X                           529
#define IDC_LIST                        1000
#define IDC_CB1                         1001
#define IDC_SLIDER                      1002
#define IDC_EDT1                        1003
#define IDC_COMBO1                      1004
#define IDC_SELECTRENDERER              1004
#define IDC_GRIDLIST                    1004
#define IDD_SELECTCAM                   1005
#define IDC_ANGLELIST                   1005
#define IDC_SELECTRENDERER2             1005
#define IDC_TREE2                       1006
#define IDC_OI                          1007
#define IDC_CHECK1                      1008
#define IDC_CLICKAPPLYOBJ               1008
#define IDC_TOPBOTTOM                   1008
#define IDC_CROSSING                    1008
#define IDC_TREE3                       1009
#define IDC_CLICKAPPLYPOLY              1009
#define IDC_LEFTRIGHT                   1009
#define IDC_CENTROID                    1009
#define IDC_HYPERLINK                   1010
#define IDC_FRONTBACK                   1010
#define IDC_GRID                        1010
#define IDC_PREVFRAME                   1011
#define IDC_ANGLE                       1011
#define IDC_LIST2                       1012
#define IDC_X                           1012
#define IDC_ADDENT                      1013
#define IDC_Y                           1013
#define IDC_CHECK2                      1014
#define IDC_TOPKEEP                     1014
#define IDC_Z                           1014
#define IDC_CREDITS                     1015
#define IDC_LEFTKEEP                    1015
#define IDC_PREVKEY                     1016
#define IDC_FRONTKEEP                   1016
#define IDC_CL1UP                       1017
#define IDC_LISTTYPE                    1018
#define IDC_DELENT                      1019
#define IDC_CHECK3                      1020
#define IDC_HIDETWEAKUV                 1020
#define IDC_CAPWORLD                    1020
#define IDC_PLAYSTOP                    1021
#define IDC_ALL                         1022
#define IDC_RENENT                      1023
#define IDC_PROP1                       1024
#define IDC_CHECK4                      1025
#define IDC_PROP2                       1026
#define IDC_NEXTKEY                     1027
#define IDC_PROP3                       1028
#define IDC_CL1DOWN                     1029
#define IDC_PROP4                       1030
#define IDC_NONE                        1031
#define IDC_PROP5                       1032
#define IDC_PAUSE                       1033
#define IDC_PROP6                       1034
#define IDC_INVERT                      1035
#define IDC_PROP7                       1036
#define IDC_TYPEEDIT                    1037
#define IDC_PROP8                       1038
#define IDC_NEXTFRAME                   1039
#define IDC_PROP9                       1040
#define IDC_CL1LEFT                     1041
#define IDC_PROP10                      1042
#define IDC_TYPECOMBO                   1043
#define IDC_PROP11                      1044
#define IDC_TYPEFILE                    1045
#define IDC_PROP12                      1046
#define IDC_NBFRAMES                    1047
#define IDC_PROP13                      1048
#define IDC_CL1RIGHT                    1049
#define IDC_PROP14                      1050
#define IDC_TYPETRUEFALSE               1051
#define IDC_PROP15                      1052
#define IDC_LISTBUDDY                   1053
#define IDC_PROP16                      1054
#define IDC_KILLKF                      1055
#define IDC_PROP17                      1056
#define IDC_TYPECOLORPICKER             1057
#define IDC_PROP18                      1058
#define IDC_SLASH                       1059
#define IDC_PROP19                      1060
#define IDC_CL1FRONT                    1061
#define IDC_PROP20                      1062
#define IDC_ADD                         1063
#define IDC_PROP21                      1064
#define IDC_DEL                         1065
#define IDC_PROP22                      1066
#define IDC_CONTAINER                   1067
#define IDC_PROP23                      1068
#define IDC_SPIN1                       1069
#define IDC_PROP24                      1070
#define IDC_TOPOY                       1070
#define IDC_SPINY                       1070
#define IDC_SPIN2                       1070
#define IDC_CL1BACK                     1071
#define IDC_TOPSX                       1071
#define IDC_SPINZ                       1071
#define IDC_SPIN3                       1071
#define IDC_PROP25                      1072
#define IDC_TOPSY                       1072
#define IDC_SPIN4                       1072
#define IDC_REN                         1073
#define IDC_LEFTOX                      1073
#define IDC_PROP26                      1074
#define IDC_LEFTOY                      1074
#define IDC_LISTCAMERA                  1075
#define IDC_LEFTSX                      1075
#define IDC_RESCALE                     1076
#define IDC_LEFTSY                      1076
#define IDC_PROP27                      1077
#define IDC_FRONTOX                     1077
#define IDC_FRONTOY                     1078
#define IDC_CBVALS                      1079
#define IDC_FRONTSX                     1079
#define IDC_PROP28                      1080
#define IDC_FRONTSY                     1080
#define IDC_OX                          1081
#define IDC_SCROLL                      1082
#define IDC_OY                          1082
#define IDC_PROP29                      1083
#define IDC_SX                          1083
#define IDC_RADIO2                      1084
#define IDC_SY                          1084
#define IDC_PROP30                      1085
#define IDC_OZ                          1085
#define IDC_CL2UP                       1086
#define IDC_SZ                          1086
#define IDC_PROP31                      1087
#define IDC_LISTPROPS                   1088
#define IDC_EDITNAME                    1089
#define IDC_SETNAME                     1090
#define IDC_DESK                        1091
#define IDC_SCRIPT                      1092
#define IDC_PROPS                       1093
#define IDC_TREE1                       1094
#define IDC_CL2DOWN                     1095
#define IDC_PROGRESS1                   1096
#define IDC_ENTLISTE                    1097
#define IDC_CBCHOOSE                    1098
#define IDC_CL2LEFT                     1099
#define IDC_DELSELECTED                 1100
#define IDC_EDIT1                       1101
#define IDC_CL2RIGHT                    1102
#define IDC_LEFTEDIT                    1102
#define IDC_FOLDEREXT                   1102
#define IDC_EDIT3                       1102
#define IDC_SCROLLBAR1                  1103
#define IDC_FRONTEDIT                   1103
#define IDC_EDIT4                       1103
#define IDC_CL2FRONT                    1104
#define IDC_EDIT5                       1104
#define IDC_SCROLLBAR2                  1105
#define IDC_CL2BACK                     1106
#define IDC_EXPLORER1                   1107
#define IDC_CHECK13                     1108
#define IDC_CHECK14                     1109
#define IDC_CHECK15                     1110
#define IDC_CHECK16                     1111
#define IDC_CHECK17                     1112
#define IDC_CHECK18                     1113
#define IDC_CHECK19                     1114
#define IDC_CHECK20                     1115
#define IDC_BUTTON1                     1116
#define IDC_BUTTON2                     1117
#define IDC_BUTTON3                     1118
#define IDC_BUTTON4                     1119
#define IDC_SLIDERZ1                    1120
#define IDC_PRECISION                   1121
#define IDC_BUTTON5                     1122
#define IDC_TAB1                        1123
#define IDC_SLIDERZ2                    1124
#define IDC_TAB2                        1124
#define IDC_ADDFOLDER                   1125
#define IDC_TAB3                        1125
#define IDC_DELFOLDER                   1126
#define IDC_TAB4                        1126
#define IDC_BUTTON6                     1127
#define IDC_ADDTOCURRENT                1128
#define IDC_TAB6                        1128
#define IDC_LIST4                       1129
#define IDC_LIST5                       1130
#define IDC_BUTTON8                     1131
#define IDC_LIST6                       1132
#define IDC_BUTTON9                     1133
#define IDC_BUTTON10                    1134
#define IDC_BUTTON11                    1135
#define IDC_BUTTON12                    1136
#define IDC_BUTTON13                    1137
#define IDC_BUTTON14                    1138
#define IDC_BUTTON7                     1139
#define IDC_SAVE                        1140
#define IDC_LOAD                        1141
#define IDC_NEW                         1142
#define IDC_SKYBOXNAME                  1143
#define IDC_DRAGGING                    1144
#define IDC_TAB5                        2000
#define IDC_LAYER1                      2001
#define IDC_LAYER2                      2002
#define IDC_LAYER3                      2003
#define IDC_LAYER4                      2004
#define IDC_LAYERSTRING                 2005
#define IDC_BROWSEBT                    2006
#define IDC_ADDPATH                     2007
#define IDC_PROJECT                     2008
#define IDC_PREFABS                     2009
#define IDC_TWEAKUV                     2010
#define IDC_SHIFTX                      2011
#define IDC_EDITSHIFTX                  2012
#define IDC_SHIFTY                      2013
#define IDC_EDITSHIFTY                  2014
#define IDC_SCALEX                      2015
#define IDC_EDITSCALEX                  2016
#define IDC_SCALEY                      2017
#define IDC_EDITSCALEY                  2018
#define IDC_ROTATE                      2019
#define IDC_EDITROTATE                  2020
#define IDC_LIBROTATE                   2021
#define IDC_LIBSHIFT                    2022
#define IDC_LIBTOPFILE                  2022
#define IDC_LIBSCALE                    2023
#define IDC_BROWSETOP                   2023
#define IDC_TOPOPA                      2024
#define IDC_TOPAFF                      2025
#define IDC_LIBLEFTFILE                 2026
#define IDC_TOPORIGINX                  2027
#define IDC_TOPORIGINY                  2028
#define IDC_TOPSIZEX                    2029
#define IDC_TOPSIZEY                    2030
#define IDC_BROWSELEFT                  2031
#define IDC_LEFTOPA                     2032
#define IDC_LEFTAFF                     2033
#define IDC_LEFTORIGINX                 2034
#define IDC_LEFTORIGINY                 2035
#define IDC_LEFTSIZEX                   2036
#define IDC_LEFTSIZEY                   2037
#define IDC_LIBFRONTFILE                2038
#define IDC_BROWSEFRONT                 2039
#define IDC_FRONTOPA                    2040
#define IDC_FRONTAFF                    2041
#define IDC_FRONTORIGINX                2042
#define IDC_FRONTORIGINY                2043
#define IDC_FRONTSIZEX                  2044
#define IDC_FRONTSIZEY                  2045
#define IDC_ORIGINX                     2046
#define IDC_ORIGINY                     2047
#define IDC_SIZEX                       2048
#define IDC_SIZEY                       2049
#define IDC_ORIGINZ                     2050
#define IDC_SIZEZ                       2051
#define IDC_TOPEDIT                     2052
#define IDC_LIBTOPWORLD                 2053
#define IDC_LIBTOPORIGIN                2054
#define IDC_LIBTOPSIZE                  2055
#define IDC_LIBLEFTORIGIN               2056
#define IDC_LIBLEFTSIZE                 2057
#define IDC_LIBLEFTWORLD                2058
#define IDC_LIBTOPOPACITY               2059
#define IDC_LIBLEFTOPACITY              2060
#define IDC_LIBFRONTOPACITY             2061
#define IDC_LIBCAPORIGIN                2062
#define IDC_LIBCAPSIZE                  2063
#define IDC_LIBFRONTSIZE                2064
#define IDC_LIBFRONTORIGIN              2065
#define IDC_LIBFRONTWORLD               2066
#define IDC_TOPOX                       2067
#define IDC_EDIT2                       2068
#define IDC_PRJBROWSELOC                2069
#define IDC_EDITY                       2069
#define IDC_LIBNEWFOLDER                2070
#define IDC_EDITZ                       2070
#define IDC_LIBNEWFOLDER2               2071
#define IDC_FOLDERNAME                  2072
#define IDC_EDITX                       2074
#define IDC_SPINX                       2075
#define IDC_LINEXY                      2076
#define IDC_OVER                        2077
#define IDC_NUM                         2078
#define IDC_CAPS                        2079
#define IDC_READ                        2083
#define IDC_INFOS                       2084
#define IDC_CONSOLE                     2085
#define IDC_PREVIEW                     2087
#define IDC_RENDER                      2088
#define IDC_RADIO1                      2089
#define IDC_RADIO3                      2090
#define IDC_PROPERTIES                  2091
#define IDC_BROWSE                      2092
#define IDC_RADIO4                      2093
#define IDC_RADIO5                      2094
#define IDC_COMBO2                      2095
#define IDC_HANDCUR                     3010
#define IDC_POINTER_SCALEUPDOWN         3011
#define IDC_POINTER_LEFTRIGHT           3012
#define IDC_POINTER_UPRIGHT             3013
#define IDC_POINTER_UPLEFT              3014
#define IDC_POINTER_ROTATE              3015
#define IDC_POINTER                     3016
#define IDC_BENDHORZ                    3017
#define IDC_BENDVERT                    3018
#define IDC_TAPERVERT                   3019
#define IDC_TAPERHORZ                   3020
#define IDC_SQUIZVERT                   3021
#define IDC_SQUIZHORZ                   3022
#define IDD_OPTIONS_INCPATHS            8603
#define IDD_SELECTION                   8604
#define IDD_MODE                        8605
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDD_OPTIONS_PREFABPATHS         8606
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define ID_OK                           10043
#define ID_CANCEL                       10044
#define IDC_LIST1                       10414
#define IDR_MARGIN_ICONS                22902
#define IDB_HOBJ                        22903
#define IDB_HSKEL                       22904
#define IDB_HBONE                       22905
#define IDB_HSHAPE                      22906
#define IDB_HSKELETTON                  22907
#define IDB_HROOT                       22908
#define IDB_HGROUP                      22909
#define IDB_HPATCH                      22910
#define IDB_HENTITY                     22911
#define IDB_DESKPREFABS                 22912
#define IDB_DESKPROJECT                 22913
#define IDB_DESKBUILD1                  22914
#define IDB_DESKHIERAR1                 22915
#define IDB_DESKMAPS1                   22916
#define IDB_DESKPREFABS1                22917
#define IDB_DESKPROJECT1                22918
#define IDB_HPREFAB                     22919
#define IDB_HSCRIPT                     22920
#define IDB_HPROJECT                    22921
#define ID__NEWGROUP                    32771
#define ID_EDIT_SELECT_BYNAME           32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_VIEW_MAPSBROWSER             32782
#define ID_VIEW_DESKFILEBROWSER         32783
#define ID__PROPERTY                    32784
#define ID_EDIT_SELECT_SINGLE           32785
#define ID_EDIT_SELECT_CIRCLE           32786
#define ID_EDIT_SELECT_QUAD             32787
#define ID_EDIT_SELECT_FENCE            32788
#define ID_READ_ONLY                    32789
#define ID_EDIT_DISABLEBSATSOL          32790
#define ID_VIEW_CONFIG_2X2              32791
#define ID_EDIT_DISABLEDRAGANDDROP      32792
#define ID_VIEW_CONFIG_1X2              32793
#define ID_VIEW_CONFIG_2X1              32794
#define ID_VIEW_CONFIG_1X3              32795
#define ID_VIEW_CONFIG_3X1              32796
#define ID_PROPERTIES                   32797
#define ID_MOVE                         32798
#define ID_EDIT_MOVE                    32799
#define ID_ROTATE                       32800
#define ID_EDIT_SCALE                   32801
#define ID_EDIT_ROTATE                  32802
#define ID_SCALE                        32803
#define ID_EDIT_DELETE                  32804
#define ID_NAME                         32805
#define ID_BUTTON32810                  32806
#define ID_HELP_TIPOFTHEDAY             32807
#define ID_VIEW_TYPE_TOP                32808
#define ID_VIEW_TYPE_BOTTOM             32809
#define ID_VIEW_TYPE_LEFT               32810
#define ID_VIEW_TYPE_RIGHT              32811
#define ID_VIEW_TYPE_FRONT              32812
#define ID_VIEW_TYPE_BACK               32813
#define ID_VIEW_TYPE_CAMERA             32814
#define ID_EDIT_MOVEROTATESCALE         32815
#define ID_VIEW_ROTATE                  32816
#define ID_VIEW_MOVESPAN                32817
#define ID_VIEW_ZOOMINOUT               32818
#define ID_VIEW_REGIONFIT               32819
#define ID_TOOLS_OPTION                 32820
#define ID_EDIT_MODE_VERTEX             32821
#define ID_EDIT_MODE_FACE               32822
#define ID_EDIT_MODE_OBJECT             32823
#define ID_EDIT_MOVEAXE                 32824
#define ID_EDIT_MOVEROTATETAPERSQUIZ    32825
#define ID_EDIT_BEND                    32826
#define ID_VIEW_EXTENDVIEW              32827
#define ID_VIEW_EXTENDSVIEWS            32828
#define ID_VIEW_RENDERMODE_MAPPED       32829
#define ID_VIEW_RENDERMODE_WIRE         32830
#define ID_VIEW_CONFIG_FULLSCREEN       32831
#define ID_BUILD_SNAP                   32832
#define ID_VIEW_MODIFY                  32833
#define ID_VIEW_SELECTION               32834
#define ID_VIEW_VIEWCONFIGURATION       32835
#define ID_VIEW_MODIFYVIEW              32836
#define ID_VIEW_EDITMODE                32837
#define ID_VIEW_BUILDBAR                32838
#define ID_VIEW_PLUGINBAR               32839
#define ID_BUTTON32844                  32840
#define IDP_CBENT                       32841
#define ID_VIEW_FLY                     32842
#define ID_ABOUT_KAPSUL                 32843
#define ID_EDIT_ENTITY_ALL              32844
#define ID_EDIT_ENTITY_CAMERA           32845
#define ID_EDIT_ENTITY_SHAPE            32846
#define ID_EDIT_ENTITY_LIGHT            32847
#define ID_EDIT_ENTITY_OBJECT           32848
#define ID_EDIT_ENTITY_PARTICLE         32849
#define ID_EDIT_ENTITY_SKELETTON        32850
#define ID_VIEW_EDITBAR                 32851
#define ID_VIEW_RENDERMODE              32852
#define ID_EDIT_DOSELECT                32853
#define ID_VIEW_GRID_VISIBLE            32854
#define ID_VIEW_GRID_INCREASEGRID       32855
#define ID_BUILD_CENTERED               32856
#define ID_BUILD_CROSSING               32857
#define ID_VIEW_GRID_DECREASEGRID       32858
#define ID_EDIT_CHOOSEMODE              32859
#define ID_VIEW_COMPILATION             32860
#define ID_VIEW_PROJECT                 32861
#define ID_VIEW_COMPILATIONTOOLS        32862
#define ID_TOOLS_SKYBOXEDITOR           32863
#define ID_VIEW_VIEWTYPES               32864
#define ID_VIEW_TYPE_PERSPECTIVE        32865
#define ID_TOOLS_PLUGINSFOLDERS         32866
#define ID__RENDER_FLATSHADED           32867
#define ID_CREATEPRIM                   32868
#define ID_VIEW_DOCKBAR                 32869
#define ID_EDIT_DELETE_BACK             32870
#define ID_EDIT_DELETE_WORD_BACK        32871
#define ID_EDIT_TAB                     32872
#define ID_EDIT_UNTAB                   32873
#define ID_EDIT_SWITCH_OVRMODE          32874
#define ID_EDIT_CHAR_LEFT               32875
#define ID_EDIT_EXT_CHAR_LEFT           32876
#define ID_EDIT_CHAR_RIGHT              32877
#define ID_EDIT_EXT_CHAR_RIGHT          32878
#define ID_EDIT_WORD_LEFT               32879
#define ID_EDIT_EXT_WORD_LEFT           32880
#define ID_EDIT_WORD_RIGHT              32881
#define ID_EDIT_EXT_WORD_RIGHT          32882
#define ID_EDIT_LINE_UP                 32883
#define ID_EDIT_EXT_LINE_UP             32884
#define ID_EDIT_LINE_DOWN               32885
#define ID_EDIT_EXT_LINE_DOWN           32886
#define ID_EDIT_SCROLL_UP               32887
#define ID_EDIT_SCROLL_DOWN             32888
#define ID_EDIT_PAGE_UP                 32889
#define ID_EDIT_EXT_PAGE_UP             32890
#define ID_EDIT_PAGE_DOWN               32891
#define ID_EDIT_EXT_PAGE_DOWN           32892
#define ID_EDIT_LINE_END                32893
#define ID_EDIT_EXT_LINE_END            32894
#define ID_EDIT_HOME                    32895
#define ID_EDIT_EXT_HOME                32896
#define ID_EDIT_TEXT_BEGIN              32897
#define ID_EDIT_EXT_TEXT_BEGIN          32898
#define ID_EDIT_TEXT_END                32899
#define ID_EDIT_EXT_TEXT_END            32900
#define ID_EDIT_FIND_PREVIOUS           32901
#define ID_EDIT_TOGGLE_BOOKMARK0        32902
#define ID_EDIT_TOGGLE_BOOKMARK1        32903
#define ID_EDIT_TOGGLE_BOOKMARK2        32904
#define ID_EDIT_TOGGLE_BOOKMARK3        32905
#define ID_EDIT_TOGGLE_BOOKMARK4        32906
#define ID_EDIT_TOGGLE_BOOKMARK5        32907
#define ID_EDIT_TOGGLE_BOOKMARK6        32908
#define ID_EDIT_TOGGLE_BOOKMARK7        32909
#define ID_EDIT_TOGGLE_BOOKMARK8        32910
#define ID_EDIT_TOGGLE_BOOKMARK9        32911
#define ID_EDIT_GO_BOOKMARK0            32912
#define ID_EDIT_GO_BOOKMARK1            32913
#define ID_EDIT_GO_BOOKMARK2            32914
#define ID_EDIT_GO_BOOKMARK3            32915
#define ID_EDIT_GO_BOOKMARK4            32916
#define ID_EDIT_GO_BOOKMARK5            32917
#define ID_EDIT_GO_BOOKMARK6            32918
#define ID_EDIT_GO_BOOKMARK7            32919
#define ID_EDIT_GO_BOOKMARK8            32920
#define ID_EDIT_GO_BOOKMARK9            32921
#define ID_EDIT_CLEAR_BOOKMARKS         32922
#define ID_EDIT_TOGGLE_BOOKMARK         32923
#define ID_EDIT_GOTO_NEXT_BOOKMARK      32924
#define ID_EDIT_GOTO_PREV_BOOKMARK      32925
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     32926
#define ID_EDIT_INDICATOR_COL           32927
#define ID_EDIT_INDICATOR_READ          32928
#define ID_EDIT_INDICATOR_CRLF          32929
#define ID_EDIT_INDICATOR_POSITION      32930
#define ID_EDIT_INDICATOR_POSITION2     32931
#define ID_VIEW_RENDER_MAPPEDOUTLINED   32932
#define ID_TOOLS_LOCALIZATION_LOC1      32935
#define ID_BUILD_CENTROID               32939
#define ID_FILE_OPENPROJECT             32940
#define ID_FILE_SAVEPROJECT             32941
#define ID_FILE_CLOSEPROJECT            32942
#define ID_FILE_CLOSEALL                32943
#define ID_TOOLS_NETUPDATE              32944
#define ID_TOOLS_BACKGROUNDWORLDCAP     32945
#define ID_FILE_NEWPROJECT              32946
#define ID_NEWFOLDER                    32947
#define ID__ADDFILESTOPROJECT           32948
#define ID__BUILD                       32949
#define ID__RUN                         32950
#define ID__OPEN                        32951
#define ID__COMPILE                     32952
#define ID__REMOVE                      32954
#define ID_WINDOW_TOGGLEFULLSCREEN      32956
#define ID__ADDFILESTOFOLDER            32957
#define ID_VIEW_UNDOVIEWCHANGE          32958
#define ID_VIEW_REDOVIEWCHANGE          32959
#define ID_EDIT_HOOKCAMERATARGET        32960
#define ID_TOOLS_RENDERINGOPTIONS       32961
#define ID_VIEW_PRIMITIVEBAR            32962
#define ID_TOOLS_MATERIALEDITOR         32964
#define ID_TOOLS_RENDERER               32965
#define ID_HELP_CONTENTS                32966
#define ID_HELP_SEARCH                  32967
#define ID_VIEW_PERSPECTIVE_UVMAPPING   32969
#define ID_VIEW_PERSPECTIVE_USERORTHO   32970
#define ID_BUILD_ANGLESNAP              32972
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_RENAMEITEM               50002
#define ID_GFX_REMOVEITEM               50003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        530
#define _APS_NEXT_COMMAND_VALUE         32973
#define _APS_NEXT_CONTROL_VALUE         2096
#define _APS_NEXT_SYMED_VALUE           300
#endif
#endif
